### ISSUE TITLE
Can't auto enable WiFi on start 

### ISSUE THREAD

**Issue by trixocroroissi** [bewue/WLANScanner#9]
1.3.0 can not start with disabled WiFi.
Android 11
===
1.2.0 works OK

**Comment by bewue** [comment]
I also noticed that there were crashes in connection with the "WLAN enable/disable" function and have now removed it. Anyway, since Android 10, apps can no longer enable/disable Wi-Fi (https://developer.android.com/reference/android/net/wifi/WifiManager#setWifiEnabled(boolean)).

There is already a new version that you can try. The update will also be available soon via Google Play and F-Droid. [WLANScanner-v1.3.1.apk](https://github.com/bewue/WLANScanner/releases/download/v1.3.1/WLANScanner-v1.3.1.apk)

**Comment by trixocroroissi** [comment]
> Anyway, since Android 10, apps can no longer enable/disable Wi-Fi

Works now, so apparently it can. :-)
